pre-release-hook = ["sh", "-c", "git cliff --tag {{version}} --output CHANGELOG.md && git add CHANGELOG.md"]
pre-release-commit-message = "chore(release): prepare for v{{version}}"
tag-message = "chore(release): v{{version}}"
