pre-release-hook = ["git", "cliff", "--tag", "{{version}}", "--output", "CHANGELOG.md"]
pre-release-commit-message = "chore(release): prepare for {{version}}"
tag-message = "chore(release): {{version}}"
